spring:
  # 数据源配置
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
  #Spring MVC配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #Redis配置
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认 9
        max-idle: 9
        # 连接池中的最小空闲连接 默认 1
        min-idle: 2
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 9
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
    host: localhost
    # 连接超时时间（毫秒）
    timeout: 10000
server:
  port: 8080
mybatis:
  configuration:
    # 驼峰命名规范 如：数据库字段是 order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappings/**/*.xml
  type-aliases-package: com.ad.system.model

# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com:
      battcn: DEBUG
mapper:
  # 主键自增回写方法,默认值MYSQL,详细说明请看文档
  identity: MYSQL
  # 设置 insert 和 update 中，是否判断字符串类型!='
  not-empty: true
  mappers: tk.mybatis.mapper.common.BaseMapper
